### ISSUE TITLE
Key-repeat loop sometimes happens

### ISSUE THREAD

**Issue by briandorsey** [gingerbeardman/strategies#1]
I'm not sure how repeatable this will be, but I got it to happen twice by opening options, changing the margin setting, then rapidly changing the deck back and forth between many options while releasing B occasionally.

**Comment by gingerbeardman** [comment]
This is fixed in forthcoming v1.2

**Comment by gingerbeardman** [comment]
Fixed in 1.2 https://gingerbeardman.itch.io/strategies/devlog/577246/changelog-12
