### ISSUE TITLE
Margin size appears to reset when changing decks. 

### ISSUE THREAD

**Issue by briandorsey** [gingerbeardman/strategies#2]
Repro: open options, set margin size to the minimum. Notice the margin is small. Change to a different deck, margin resets to the default, while the option remains set to the minimum.

**Comment by gingerbeardman** [comment]
This is fixed in the forthcoming v1.2

**Comment by gingerbeardman** [comment]
Fixed in 1.2 https://gingerbeardman.itch.io/strategies/devlog/577246/changelog-12
